### ISSUE TITLE
CompleteInventory, well done but some issues

### ISSUE THREAD

**Issue by DanSteph1024** [Krsmanovic-S/Complete-Inventory-Documentation#1] opened 2023-06-27 01:51 UTC
Dear Stefan,
I bought your project to fit my need, it's well done but I have some issues:

1-If I design a bigger chest with BasicSlotAmount=36 and MaximumColumiCount=6, after visiting the big one, the small one don't resize properly. See image below.
2-"Slot" Array never cease to increase, again see image.

Also Request: would it be possible to release a dropped item at the world point where the mouse is released ? As it is now, it's not usable for a real game.

Much thanks & best regards

Dan
![Bug_1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/5964e12d-6bd9-4c68-ad0f-70070890d20f)
![Bug_2](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/42ef30bd-7c9c-493d-bfc6-aec0e0a2b997)
![Bug_3](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/a51b9a23-a1f2-4ae4-9cc5-b90dd455b7af)
![Bug_4](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/e297bf7c-ff5d-4dd3-8685-1f1019a84b7f)
![Bug_5](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/8599f42a-8541-4cda-8223-fd1462103355)

**Comment by Krsmanovic-S** [comment] 2023-06-27 17:12
Hey Dan, thanks for pointing out these issues, was an oversight on my part. I've found the cause for the slot creation as well as the bigger chest problem. You should be able to create chests of different sizes on a **per instance basis** now as well which you can see here:

![Capture1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/e135d128-4e44-4123-aa7b-0b8e7813d6a1)

As far as the slots and how it was fixed, you can see it inside the **WGB_Container_Inventory**:

![Capture](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/c628cbc4-c111-411c-a7db-2043a9de6f76)

Slots for the container can vary of course, so the slots needed to be cleared every time the widget was hidden. This way you can have as many containers with different sizes and all should be good! Keep in mind that you can also do this for the Players inventory, for example if you do decide that your Player can increase his inventory size, I'd suggest adding a branch that checks whether the size changed and if so, apply the same logic as the function for the container widgets. 

> Also Request: would it be possible to release a dropped item at the world point where the mouse is released ? As it is now, it's not usable for a real game.

I didn't include this in the plugin as it can be very specific to what kind of game you are making. If you are looking for this behaviour for your game, I'd suggest looking into [this](https://forums.unrealengine.com/t/how-do-i-spawn-an-actor-at-the-mouse-position-on-drop/368409) post on the forums. You can put this inside the **WGB_HUD** and experiment with it there since the drops only occur when the HUD registers the **On_Drop event**. Alternatively, you could also implement some logic in the **BP_ItemActor** (BeginPlay specifically) and take it from there.

I have sent the updates to Epic, as soon as they approve them you should be able to get them. If for some reason the update doesn't come to you automatically, you could just reinstall the plugin to the engine.

Glad you are enjoying the plugin and best of luck to you Dan!

**Comment by DanSteph1024** [comment] 2023-06-28 03:02
Hello Stefan,

Much thank for your quick update, yet epic still didn't updated the files. Once done I'll test everything and tell you back here, so I keep this open.
I'm on an indie project, I'm very experienced in C++, but new to unreal and my weak spot are the blueprints and UMG in particular, Would you be open in the incoming week/month to an upwork.com on my UI ? (paid task work).

Cheers,

Dan

**Comment by Krsmanovic-S** [comment] 2023-06-28 03:36
I still haven't recieved anything from Epic so it might take some time. If you want to update your version instead of waiting, I can help with that. The fix for the widget is creating a function and binding an event to fire it every time the visibility is changed so let's start with that:

![Capture1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/5bf7a7e3-025e-4bbc-9f31-fc2401f6f7e9)

Inside the **WGB_ContainerInventory**, you can create this same function. After that we just need to hook it up like so:

![Capture3](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/e8ce501d-1950-4ef5-8630-975d40f01c6e)

And that solves our problem! Previously, as you pointed out, the container widget wasn't resetting the slots at all. Now it should update itself accordingly and display the proper sizes in the UI. As for the editable size on the chests, it is just a matter of changing the size and the column count variables to be editable anywhere:

![Capture4](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/b6d36f22-6b79-4086-9697-be84ebb36a6c)

The above is inside **InventoryComponent.h** header file. If you have any additional issues or questions don't hesitate to post them here, I will have a look as soon as I can!

> I'm on an indie project, I'm very experienced in C++, but new to unreal and my weak spot are the blueprints and UMG in particular, Would you be open in the incoming week/month to an upwork.com on my UI ? (paid task work).

I'd like to hear more about it for sure! If you could send me some more details on my email I would appriciate it.

- krsmanovic1998@gmail.com  

Regards,

Stefan

**Comment by DanSteph1024** [comment] 2023-06-28 05:30
Your solution work like a charm, much thank sir.
The problem with the "drop on mouse" is that the Player Controller does not receive mouse input during drag operation. The widgets take over.
There is a solution here, but I don't have any idea how to make it, if you can help ?
https://forums.unrealengine.com/t/hit-result-under-cursor-while-dragging-widgets/451561

Everyone expect a drop at mouse pos, so imho it's not so project dependent, and it could be a nice addition to your addon  :) (and you could raise the price)

I tested this in BeginPlay of ItemActor and effectively, it doesn't receive mouse position:
_FHitResult HitResult;
FCollisionQueryParams QueryParams;
QueryParams.AddIgnoredActor(this);
APlayerController* PlayerController = UGameplayStatics::GetPlayerController(GetWorld(), 0);
FVector mouseLocation, mouseDirection;
PlayerController->DeprojectMousePositionToWorld(mouseLocation, mouseDirection);
GetWorld()->LineTraceSingleByChannel(HitResult, mouseLocation + mouseDirection * 50, mouseLocation + mouseDirection * 9000, ECC_Visibility, QueryParams);_


For my project, I'm three month into it while learning unreal but I have a long experience with unity and C++, the result is very good yet, but there are ton of things to do and the UI will be a huge point and not my favorite subject.  I'll not fix it until I have a complete gameplay, if you're interested I can contact you in the meaning time so we can meet at upwork ?

Best regards and much thanks again,

Dan

**Comment by Krsmanovic-S** [comment] 2023-06-28 22:07
> The problem with the "drop on mouse" is that the Player Controller does not receive mouse input during drag operation. The widgets take over.

The solution is very simple, you could get the **Mouse Position** with just the **GetScreenSpacePosition** node. The widgets do overtake the mouse input when you drag the items which means you can get the mouse position there. The drops occur when the event **On_Drop** is triggered by the **HUD**, so this is the perfect place. Simply add the node here **(WGB_HUD -> On_Drop function)**, connect the **Pointer Event** to it and you are done:

![Capture](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/c030fd01-b5c6-4a37-8dd4-369a073ce067)

You can then just pass this in as a parameter when creating the item and from there it is all C++, which is your familiar teritory. If you want to create a variable that is exposed when creating an object (e.g. you want to add this mouse position as a spawn value for the Item Actor), you can do it like so:

![Capture1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/a49b7e3b-e44e-44b0-9a1c-da7864bf99be)

Basically this meta flag is all you need and you should be good to go!

> Everyone expect a drop at mouse pos, so imho it's not so project dependent

I will look to implement this at some point, been experimenting recently with it to not so smooth results so I won't ship it yet. I will however tinker around with it and see what I can get out of it, how it looks etc..

If this resolved all of your issues for now, do close the issue on git. Of course if anything else happens feel free to open a new one, I'll be on it as soon as I can.

> For my project, I'm three month into it while learning unreal but I have a long experience with unity and C++, the result is very good yet, but there are ton of things to do and the UI will be a huge point and not my favorite subject. I'll not fix it until I have a complete gameplay, if you're interested I can contact you in the meaning time so we can meet at upwork ?

Yes, I'd like to here more about it, drop me a message on upwork ([profile](https://www.upwork.com/freelancers/~0103f3818f5083b3fe)).

Take care Dan!

**Comment by DanSteph1024** [comment] 2023-06-28 22:23
Much thanks for your help Stefan, I registered your upwork profile.
Yet I have a complete working "chest & items" basis, so I'll continue with the whole gameplay and contact you in the meaning time.

Best regards

Dan

**Closed as completed** 2023-06-28 22:23 UTC
